exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - vendor
  - "*.iml"
  - fetch_yt_preview
  - .github

highlighter: rouge
markdown: kramdown

external: https://sherollari.it
#external: http://192.168.1.3:4000
baseurl: ""

title: Julian Sherollari
description: Computer & Automation Enginieer studied at the Marche Polytechnic University, semester abroad at Augsburg University of Applied Sciences, intern at The Qt Company during the Google summer of code program.

author:
  name: Julian Sherollari
  pronunciation: "['dʒuːljən ˈʃerəllari]"
  profession: Software Enginieer
  social:
    - name: LinkedIn
      icon: fa-linkedin
      url: https://www.linkedin.com/in/jdotsh
    - name: Twitter
      icon: fa-twitter
      url: https://twitter.com/JSherollari
    - name: Github
      icon: fa-github-alt
      url: https://github.com/jdotsh
    - name: Mail
      icon: fa-envelope
      url: "mailto:julian@sherollari.it"
      notarget: true
  skills:
    - "#javascript"
    - "#c++"
    - "#python"
    - "#machinelearning"
    - "ai"

  twitter: JSherollari
  github: jdotsh
  avatar: /assets/img/card.jpg

sidebar:
  links:
    - name: Home
      link: /
      rel: nofollow
    - name: Notes
      link: /notes/
    - name: About
      link: /about/
      rel: nofollow
    - name: Privacy Policy
      link: /privacy/
      rel: nofollow

plugins:
  - jekyll-redirect-from
